import { createRequire } from 'node:module';
import { mkdirSync, writeFileSync } from 'node:fs';
import assert from 'node:assert/strict';
import {previewPdf} from './fixtures.js';
const require = createRequire(import.meta.url);
const { chromium } = require(process.env.PLAYWRIGHT_PATH || 'playwright-core');
const base = process.env.TEST_URL || 'http://127.0.0.1:5175';
assert.notEqual(new URL(base).port,'5173','Use an isolated QA server, never the daily database.');
mkdirSync('artifacts',{recursive:true});
const browser = await chromium.launch({channel:'chrome',headless:true});
const context = await browser.newContext({viewport:{width:1440,height:1050},deviceScaleFactor:1});
const page = await context.newPage();
const errors=[];
page.on('pageerror',error=>errors.push(error.message));
const passed=[];
const check=(name)=>{passed.push(name);console.log(`PASS ${name}`);};
async function visible(locator){await locator.waitFor({state:'visible',timeout:12000});}
async function clickNav(label){await page.locator('.sidebar').getByRole('link',{name:label,exact:true}).click();}
async function overflow(){return page.evaluate(()=>({width:innerWidth,document:document.documentElement.scrollWidth,violations:[...document.querySelectorAll('main *')].filter(e=>{const r=e.getBoundingClientRect();return r.width&&r.right>innerWidth+1;}).map(e=>({tag:e.tagName,cls:e.className})).slice(0,8)}));}
try {
  await page.goto(base+'/');
  const needsSetup=(await (await context.request.get(base+'/api/auth/status')).json()).setupNeeded;
  if(needsSetup)await page.getByLabel('你的姓名').fill('本地测试管理员');
  await page.getByLabel('邮箱',{exact:true}).fill('qa-admin@example.test');
  await page.getByLabel('密码',{exact:true}).fill('Local-test-password-123');
  await page.getByRole('button',{name:needsSetup?'创建管理员并进入':'进入资料中心',exact:true}).click();
  await visible(page.getByRole('heading',{name:'最近更新',exact:false}));
  // Clean only this test's prior artifacts in the isolated browser-test database.
  const initialResources=(await (await context.request.get(base+'/api/resources')).json()).resources;
  for(const r of initialResources){if(r.title.startsWith('浏览器测试 ·'))await context.request.delete(`${base}/api/resources/${r.id}`);if(r.favorite)await context.request.post(`${base}/api/resources/${r.id}/favorite`,{data:{}});}
  await page.reload();await visible(page.getByRole('heading',{name:'最近更新',exact:false}));
  await page.screenshot({path:'artifacts/home-desktop.png',fullPage:true});
  assert.equal((await overflow()).document,1440);
  check('administrator bootstrap and desktop dashboard');
  if(await page.getByRole('switch',{name:'装饰动效'}).isChecked())await page.getByRole('switch',{name:'装饰动效'}).click();
  assert.equal(await page.locator('html').getAttribute('data-motion'),'off');
  check('motion toggle');
  await page.getByRole('textbox',{name:'搜索资料',exact:true}).fill('STM32');
  await page.getByRole('button',{name:'搜索',exact:true}).click();
  await visible(page.getByRole('heading',{name:'“STM32” 的搜索结果'}));
  assert.equal(await page.locator('.resource-row').count(),1);
  await page.locator('.resource-main').click();
  await visible(page.getByRole('heading',{name:'STM32 开发入门与外设基础',exact:true}));
  assert.equal(await page.getByRole('link',{name:'访问原始资料'}).getAttribute('target'),'_blank');
  await page.getByRole('button',{name:'链接无法访问？'}).click();
  await visible(page.getByText('本站无法实时验证外站状态。',{exact:false}));
  await page.getByRole('link',{name:'返回资料列表'}).click();
  assert.equal(await page.getByRole('textbox',{name:'搜索资料'}).inputValue(),'STM32');
  assert.equal(await page.locator('.resource-row').count(),1);
  check('search, external link detail and preserved filters');
  await page.getByRole('button',{name:'收藏 STM32 开发入门与外设基础',exact:true}).click();
  await page.locator('.sidebar a[href="/favorites"]').click();
  await visible(page.getByRole('heading',{name:'我的收藏',exact:false}));
  assert.equal(await page.locator('.resource-row').count(),1);
  check('favorites route');
  await page.locator('.sidebar a[href="/resources"]').click();
  await page.getByRole('combobox',{name:'筛选资料领域'}).focus();
  await page.keyboard.press('Space');
  await page.waitForFunction(()=>document.activeElement?.getAttribute('role')==='option');
  await page.keyboard.press('Home');
  await page.waitForFunction(()=>document.activeElement?.textContent==='全部领域');
  await page.keyboard.press('ArrowDown');
  await page.waitForFunction(()=>document.activeElement?.textContent==='期末复习');
  await page.keyboard.press('Enter');
  await page.waitForURL('**/resources?domain=academic');
  assert.equal(await page.locator('.resource-row').count(),3);
  await page.getByRole('radio',{name:'卡片视图'}).click();
  assert.equal(await page.locator('.resource-grid .resource-row').count(),3);
  await page.getByRole('textbox',{name:'搜索资料'}).fill('no-such-resource-123');
  await page.getByRole('button',{name:'搜索',exact:true}).click();
  await visible(page.getByRole('heading',{name:'暂时没有找到匹配的资料'}));
  check('domain filtering, grid toggle, empty result');
  await page.goto(base+'/resources/new');
  await page.getByRole('button',{name:'发布资料',exact:true}).click();
  await page.getByLabel('资料标题',{exact:false}).fill('浏览器测试 · 实际上传文件');
  await page.getByRole('button',{name:'发布资料',exact:true}).click();
  await visible(page.getByText('请至少选择一个文件',{exact:true}));
  await page.getByLabel('选择上传文件').setInputFiles({name:'learning.txt',mimeType:'text/plain',buffer:Buffer.from('Uploaded through the real interface.\nRM learning resource test.')});
  await page.getByLabel('资料简介').fill('浏览器自动验证文件上传、预览、编辑和删除。');
  await page.route('**/api/resources',route=>route.request().method()==='POST'?route.abort('failed'):route.continue());
  await page.getByRole('button',{name:'发布资料',exact:true}).click();
  await visible(page.getByText('网络连接失败，文件已保留在表单中，请重试',{exact:true}));
  await page.unroute('**/api/resources');
  await page.getByRole('button',{name:'重试发布'}).click();
  await visible(page.getByRole('heading',{name:'浏览器测试 · 实际上传文件',exact:true}));
  await visible(page.getByText('Uploaded through the real interface.',{exact:false}));
  const uploadId=page.url().split('/').pop();
  const downloadPromise=page.waitForEvent('download');
  await page.getByRole('link',{name:'下载原文件'}).click();
  const download=await downloadPromise;assert.equal(download.suggestedFilename(),'learning.txt');
  check('required fields, failed upload retry, text preview, actual download');
  await page.getByRole('link',{name:'编辑资料',exact:true}).click();
  await page.getByLabel('资料标题',{exact:false}).fill('浏览器测试 · 更新后的资料');
  await page.getByRole('button',{name:'保存修改'}).click();
  await visible(page.getByRole('heading',{name:'浏览器测试 · 更新后的资料'}));
  await page.getByRole('button',{name:'删除资料',exact:true}).click();
  await visible(page.getByRole('alertdialog'));
  await page.getByRole('button',{name:'保留资料'}).click();
  await page.getByRole('button',{name:'删除资料',exact:true}).click();
  await page.getByRole('button',{name:'确认删除'}).click();
  await visible(page.getByRole('heading',{name:'全部资料',exact:false}));
  check('edit, delete confirmation and deletion');
  await page.goto(base+'/resources/sample-5');
  const img=page.locator('.image-preview img');await visible(img);await img.evaluate(e=>e.decode());
  assert.ok(await img.evaluate(e=>e.naturalWidth>0));
  await page.screenshot({path:'artifacts/detail-desktop.png',fullPage:true});
  check('image preview');
  await page.goto(base+'/resources/new');
  await page.getByLabel('资料标题',{exact:false}).fill('浏览器测试 · PDF 与附件预览');
  await page.getByLabel('选择上传文件').setInputFiles([
    {name:'preview.pdf',mimeType:'application/pdf',buffer:previewPdf()},
    {name:'example.bin',mimeType:'application/octet-stream',buffer:Buffer.from([1,2,3,4])}
  ]);
  await page.getByRole('button',{name:'发布资料',exact:true}).click();
  await visible(page.getByRole('heading',{name:'浏览器测试 · PDF 与附件预览'}));
  await visible(page.getByTitle('PDF 预览：preview.pdf'));
  const pdfUrl=await page.getByTitle('PDF 预览：preview.pdf').getAttribute('src');
  const pdfResponse=await context.request.get(base+pdfUrl);
  assert.equal(pdfResponse.status(),200);assert.equal(pdfResponse.headers()['content-type'],'application/pdf');assert.ok((await pdfResponse.body()).toString().startsWith('%PDF-1.4'));
  await page.getByRole('button',{name:'预览无法显示？'}).click();
  await visible(page.getByRole('heading',{name:'预览暂时不可用'}));
  await page.getByRole('button',{name:'example.bin',exact:true}).click();
  await visible(page.getByText('此格式暂不支持在线预览，请下载后查看。',{exact:true}));
  await page.getByRole('button',{name:'删除资料',exact:true}).click();await page.getByRole('button',{name:'确认删除'}).click();
  await visible(page.getByRole('heading',{name:'全部资料',exact:false}));
  check('PDF response and preview, preview failure fallback, unsupported attachment');
  const temporary=[];
  for(let i=0;i<3;i++){const result=await context.request.post(base+'/api/resources',{multipart:{title:`浏览器测试 · 分页 ${i}`,domain:'rm',category:'通用工具',kind:'link',url:'https://example.org',description:'分页测试',tags:'[]'}});temporary.push((await result.json()).id);}
  await page.goto(base+'/resources');
  await visible(page.locator('.pagination'));
  assert.equal(await page.locator('.resource-row').count(),10);
  await page.getByRole('button',{name:'下一页',exact:true}).click();
  assert.equal(await page.locator('.resource-row').count(),2);
  await page.getByRole('button',{name:'上一页',exact:true}).click();
  assert.equal(await page.locator('.resource-row').count(),10);
  for(const id of temporary)await context.request.delete(`${base}/api/resources/${id}`);
  check('real pagination');
  await page.goto(base+'/admin');
  await page.getByRole('button',{name:'创建邀请链接'}).click();
  const join=await page.getByLabel('新邀请链接').inputValue();
  const guest=await browser.newContext({viewport:{width:1440,height:950}});const guestPage=await guest.newPage();
  guestPage.on('pageerror',error=>errors.push(error.message));
  await guestPage.goto(join);
  await guestPage.getByLabel('你的姓名').fill('测试成员');await guestPage.getByLabel('邮箱',{exact:true}).fill(`qa-member-${Date.now()}@example.test`);await guestPage.getByLabel('密码',{exact:true}).fill('Member-test-password-123');
  await guestPage.getByRole('button',{name:'注册并进入资料中心'}).click();
  await visible(guestPage.getByRole('heading',{name:'最近更新',exact:false}));
  await guestPage.goto(base+'/admin');await visible(guestPage.getByRole('heading',{name:'需要管理员权限'}));
  await guestPage.goto(base+'/resources/sample-1/edit');await visible(guestPage.getByRole('heading',{name:'无法编辑资料'}));
  check('invite registration and member permission UI');
  await guestPage.goto(join);await visible(guestPage.getByText('邀请已失效或已被使用，请联系管理员重新邀请',{exact:true}));
  check('consumed invitation UI');
  await guest.close();
  await page.goto(base+'/');await page.getByRole('radio',{name:'列表视图'}).click();
  await page.screenshot({path:'artifacts/home-desktop.png',fullPage:true});
  await page.setViewportSize({width:768,height:1024});
  assert.equal((await overflow()).document,768);
  await page.screenshot({path:'artifacts/home-tablet.png',fullPage:true});
  await page.setViewportSize({width:360,height:800});
  assert.equal((await overflow()).document,360,JSON.stringify(await overflow()));
  await page.screenshot({path:'artifacts/home-mobile.png',fullPage:true});
  await page.getByRole('button',{name:'打开导航'}).click();
  await visible(page.locator('[data-mobile="true"]'));
  await page.keyboard.press('Escape');await page.locator('[data-mobile="true"]').waitFor({state:'hidden'});
  assert.equal(await page.getByRole('button',{name:'打开导航'}).evaluate(el=>el===document.activeElement),true);
  await page.goto(base+'/resources');await page.getByRole('button',{name:'筛选',exact:true}).click();
  await visible(page.getByRole('dialog'));
  await page.getByRole('dialog').getByRole('combobox',{name:'筛选资料领域'}).click(); await page.getByRole('option',{name:'RM 学习',exact:true}).click();
  await page.getByRole('button',{name:'查看结果'}).click();
  assert.equal(await page.locator('.resource-row').count(),6);
  assert.equal((await overflow()).document,360,JSON.stringify(await overflow()));
  await page.goto(base+'/resources/new');
  assert.equal((await overflow()).document,360,JSON.stringify(await overflow()));
  await page.locator('h1').click();await page.evaluate(()=>scrollTo(0,0));
  await page.screenshot({path:'artifacts/upload-mobile.png',fullPage:true});
  await page.goto(base+'/resources/sample-5');await visible(page.locator('.image-preview img'));
  assert.equal((await overflow()).document,360,JSON.stringify(await overflow()));
  check('768px and 360px layouts, mobile drawer and filter modal');
  await page.setViewportSize({width:1440,height:1050});
  await page.goto(base+'/');
  await page.getByRole('switch',{name:'装饰动效'}).check();
  await page.emulateMedia({reducedMotion:'reduce'});await page.reload();
  assert.equal(await page.evaluate(()=>matchMedia('(prefers-reduced-motion: reduce)').matches),true);
  assert.equal(await page.locator('.entry-card').first().evaluate(el=>getComputedStyle(el).transitionDuration),'0s');
  await page.keyboard.press('/');assert.equal(await page.getByRole('textbox',{name:'搜索资料'}).evaluate(el=>el===document.activeElement),true);
  check('reduced motion and keyboard search shortcut');
  const unauth=await browser.newContext();const login=await unauth.newPage();
  await login.goto(base+'/resources/sample-2');await visible(login.getByRole('heading',{name:'欢迎回来，队友。'}));
  await login.getByLabel('邮箱',{exact:true}).fill('qa-admin@example.test');await login.getByLabel('密码',{exact:true}).fill('Local-test-password-123');await login.getByRole('button',{name:'进入资料中心',exact:true}).click();
  await visible(login.getByRole('heading',{name:'STM32 开发入门与外设基础',exact:true}));
  await unauth.close();
  check('deep link resumes after login');
  assert.deepEqual(errors,[]);
  writeFileSync('artifacts/browser-results.json',JSON.stringify({passed,errors},null,2));
  console.log(JSON.stringify({passed:passed.length,errors}));
} catch(error) {await page.screenshot({path:'artifacts/browser-failure.png',fullPage:true});console.error(error);process.exitCode=1;}
finally{await browser.close();}
